"""
tweets for ToughLoveBot by elias g. and elliot p. These tweets are by elliot p.
with minimal editing by elias g.

authors: elias g. and elliot p.
version: 21.11.16
"""

tweets = ["NOTICE HOW THE DIRT SMELLS. NICE.",
          "NOTICE HOW THE SUNLIGHT SHINES THROUGH THE LEAVES. SO PRETTY.",
          "THAT CLOUD LOOKS LIKE A WEIRD DUCK. NEAT.",
          "HEY. SOMETIMES THINGS ARE GOING TO BE HARD, BUT THAT WON’T LAST FOREVER. YOU JUST NEED TO BE STRONG, AND  EVENTUALLY IT'LL PASS.",
          "DO NOT EAT THAT HORSESHIT. EAT SOME FRUIT OR SOMETHING. YOU'RE STILL GOING TO NEED THESE ORGANS WHEN YOU'RE EIGHTY.",
          "IT’S OKAY TO SEEK EMOTIONAL SUPPORT FROM THE PEOPLE YOU LOVE. NEEDING THE HELP OF OTHERS IS NOT A SIGN OF WEAKNESS.",
          "REMEMBER THAT THIS ISN’T JUST A BOT. A PERSON MADE THIS, AND THAT PERSON LOVES YOU, WHOEVER YOU ARE.",
          "REMEMBER TO TEXT WHOEVER BACK",
          "DRINK SOME FUCKING WATER. YOU'RE DEHYDRATED AND IT'S MAKING YOU GRUMPY.",
          "MAYBE READ GODDAMN A BOOK ONCE IN AWHILE.",
          "TAKE SOME DEEP-ASS BREATHS.",
          "GO OUTSIDE AND LOOK AT SOME PLANTS AND SHIT. NOTICE HOW THE DIRT SMELLS.",
          "I FUCKING BELIEVE IN YOU.",
          "TALK TO SOMEONE. STEWING IN YOUR OWN EMOTIONS WILL ONLY INCREASE FEELINGS OF ISOLATION.",
          "YOU’VE BEEN SITTING IN THAT CHAIR FOR A WHILE. STAND UP AND WALK AROUND A LITTLE. MAYBE DO SOME PUSH-UPS.",
          "STOP COMING UP WITH REASONS WHY NOT AND JUST DO IT ALREADY.",
          "MAKE A SNACK. NO, NOT SOMETHING SHIT LIKE THAT. SOMETHING ACTUALLY GOOD FOR YOU. SOMETHING WITH FIBER.",
          "ASKING FOR HELP IS PERFECTLY VALID. NO ONE WILL THINK LESS OF YOU FOR IT.",
          "YOU KNOW THAT THING YOU’VE BEEN PUTTING OFF DOING FOR WEEKS. DO IT. RIGHT NOW. NO EXCUSES.",
          "TAKE A MENTAL HEALTH DAY. SAY YOU’RE SICK OR SOMETHING. REMEMBER, THE MOST COMMON AND BELIEVABLE ALIMENT IS “STOMACH STUFF”.",
          "PUT SOME SOCKS NEAR THE HEATER SO THAT THEY’RE ALL WARM LATER. SO TOASTY.",
          "DO YOU HAVE MEDS. IF SO, REMEMBER TO TAKE THEM. IF NOT, EAT A VITAMIN OR SOMETHING.",
          "BREATHE. JUUUST BREATHE.",
          "YOU’RE NEVER AS ALONE AS YOU MIGHT THINK YOU ARE.",
          "ARE YOU BREATHING FASTER THAN NORMAL? CALM THAT MESS DOWN. SLOW, EVEN BREATHS.",
          "YOU KNOW THAT PERSON YOU HATE. WELL I TRUST YOUR JUDGMENT ENOUGH TO HATE THEM TOO. THEY’RE THE WORST.",
          "YOUR FRIENDS LOVE YOU. DOUBTING THAT WILL ONLY MAKE THINGS WORSE. RECEIVING AFFECTION IS NOT A WEAKNESS.",
          "NOTHING LASTS FOREVER, BAD OR GOOD. ENJOY THE GOOD WHILE IT LASTS AND KNOW THE BAD IS ALWAYS TEMPORARY.",
          "HEY. I LOVE YOU.",
          "HEYYYYY. JUST A REMINDER THAT YOU HAVE TALENTS UNIQUE TO YOU, THAT NO ONE ELSE IN THE WORLD HAS.",
          "GIVE SOMEONE A HIGH FIVE. THE TRICK IS TO FOCUS ON THEIR ELBOWS, THEN YOU NEVER MISS.",
          "CLEAN OUT YOUR INBOX. IT’LL GIVE YOU PEACE OF MIND.",
          "HERE IS A LINK TO A VIDEO OF A CAT AND A CHICKEN WHO ARE FRIENDS. LOOK AT IT. SO CUTE. https://www.youtube.com/watch?v=sNYIAQcCF9",
          "GO OUTSIDE AND LOOK AT SOME PLANTS AND NATURE AND SHIT.",
          "GO OUTSIDE AND FIND SOME RUNNING WATER AND MEDITATE.",
          "GO OUTSIDE AND SIT UNDER A TREE AND THINK HAPPY THOUGHTS.",
          "ARE YOU HUNGRY OR ARE YOU JUST BORED. REALLY THINK ABOUT IT.",
          "HAVE YOU ATE TODAY? PLEASE EAT TODAY.",
          "REMEMBER, YOU DESERVE TO FEEL GOOD TOO.",
          "REMEMBER THAT ONE JERK? YEAH, THEY CAN GO TO HELL AND THEIR OPINION DOESN'T MATTER.",
          "AT THE END OF THE DAY, THE DECISIONS THAT MATTER THE MOST ARE THOSE THAT MAKE YOU HAPPY.",
          "IT'S NOT OKAY FOR YOUR SIGNIFICANT OTHER TO BLAME YOU FOR EVERYTHING.",
          "LOVE SOMEONE WHO LOVES YOU BACK. SETTLE FOR NO LESS, NEVER EVER.",
          "YOU DESERVE TO FEEL LOVED AND TO BE LOVED. DON'T DATE SOMEONE WHO MAKES YOU FEEL OTHERWISE.",
          "CALL YOUR MOM. SHE LOVES YOU AND WANTS TO KNOW HOW YOU ARE DOING.",
          "CALL YOUR DAD. HE LOVES YOU AND WANTS TO KNOW HOW YOU ARE DOING.",
          "IF YOU DON'T HAVE A DAD, THAT'S OKAY. IT'S NOT YOUR FAULT AND IT'S HIS LOSS.",
          "IF YOU DON'T HAVE A MOM, THAT'S OKAY. IT'S NOT YOUR FAULT AND IT'S HER LOSS.",
          "NOT STRAIGHT? GREAT. DON'T LET ANYONE LET YOU FEEL WRONG ABOUT THAT.",
          "MAKE THEM RESPECT YOUR PRONOUNS.",
          "SPEAK UP, EVEN IF IT MEANS YOUR VOICE CRACKS. YOU ARE STRONG.",
          "REMEMBER THAT COUSIN YOU PLAYED WITH A LOT WHEN YOU WERE A KID? CALL THEM AND CATCH UP.",
          "IF YOU ARE STRUGGLING AND HAVE NO ONE TO GO TO, REMEMBER THERE ARE SUPPORT GROUPS YOU CAN REACH OUT TO.",
          "NEVER LET SOMEONE MAKE YOU FEEL BAD ABOUT WHERE YOU ARE FROM, WHAT GENDER YOU ID WITH, OR THE TONE OF YOUR SKIN.",
          "YOU ARE AMAZING, FUCK YEAH.",
          "FUCK WHAT THE HATERS SAID.",
          "THE REPORTS ARE IN AND YOU ARE DOING GREAT, KEEP IT UP.",
          "THE REPORTS ARE IN AND YOU GOT THIS. KEEP HOLDING ON.",
          "IF YOU ARE STRUGGLING, YOU ARE MAKING PROGRESS. KEEP FIGHTING.",
          "FIGHT THE GOOD FIGHT. DO YOUR HOMEWORK.",
          "FIGHT THE GOOD FIGHT. STAND UP FOR YOURSELF AND WHAT YOU BELIEVE IN.",
          "MEND THE FIRST BREAK, KILL THE FIRST SNAKE, AND CONQUER EVERYTHING YOU UNDERTAKE.",
          "WHEREVER YOU WIND UP IN LIFE, YOU’LL FIND A WAY TO BE HAPPY, AND BE CONTENTED WITH THE CHOICES YOU MADE."]

worriedReplies = ["FEAR ONLY CLOUDS THE MIND WITH DOUBT. SEE CLEARLY. BREATHE IN.",
                  "YOUR ANXIETIES ONLY DECEIVE YOU.",
                  "THINGS ARE NEVER AS BAD AS THEY SEEM.",
                  "YOU’RE STRONG. YOU CAN FIGHT BACK.",
                  "AS LONG AS YOU NEVER GIVE UP, YOU WON’T BE TAKEN DOWN WITHOUT A FIGHT.",
                  "YOU’RE STRONG. YOU CAN DO THIS.",
                  "YOU CAN SURVIVE THIS.",
                  "IT’S GOING TO BE OKAY",
                  "THINGS WILL GET BETTER. I PROMISE.",
                  "IT MAY NOT BE OKAY NOW, BUT IT WILL BE SOON.",
                  "I LOVE YOU. AND SO DO OTHERS.",
                  "BREATHE DEEPLY."]

sickReplies = ["PAIN EXISTS ONLY IN THE MIND. YOU GOT THIS.",
               "HEAL THE MIND AND THE REST WILL FOLLOW. GIVE YOURSELF A BREAK.",
               "FOCUS INWARD AND ONWARD.",
               "THE BODY’S ABILITY TO HEAL ITSELF IS BETTER THAN ANYTHING MADE BY HUMAN HANDS.",
               "IT’S OKAY TO SLOW DOWN AND GIVE YOURSELF TIME TO RECOVER.",
               "THERE ARE OTHERS YOU CAN RELY ON FOR SUPPORT.",
               "YOU’RE STRONG. YOU CAN DO THIS.",
               "YOU CAN SURVIVE THIS.",
               "IT’S GOING TO BE OKAY",
               "THINGS WILL GET BETTER. I PROMISE.",
               "IT MAY NOT BE OKAY NOW, BUT IT WILL BE SOON.",
               "I LOVE YOU. AND SO DO OTHERS.",
               "BREATHE DEEPLY."]

lonelyReplies = ["MORE PEOPLE LOVE YOU THEN YOU KNOW.",
                 "DON’T BE AFRAID TO REACH OUT.",
                 "WANTING TO BE LOVED IS NOT A WEAKNESS.",
                 "OTHER PEOPLE ARE NEVER AS SCARY AS THEY SEEM.",
                 "IF YOU’VE BEEN HURT IN THE PAST, KNOW THAT YOU SURVIVED IT. AND THIS TIME, YOU CAN PREVENT IT.",
                 "YOU’RE STRONG. YOU CAN DO THIS.",
                 "YOU CAN SURVIVE THIS.",
                 "IT’S GOING TO BE OKAY",
                 "THINGS WILL GET BETTER. I PROMISE.",
                 "IT MAY NOT BE OKAY NOW, BUT IT WILL BE SOON.",
                 "I LOVE YOU. AND SO DO OTHERS.",
                 "BREATHE DEEPLY."]

followerReplies = ["YOU ARE AN AMAZING PERSON, YOU GOT THIS.",
                   "IS YOUR SHIT TOGETHER? GET YOUR SHIT TOGETHER. YOU CAN DO IT.",
                   "DO YOU HAVE SOME KIND OF ASSIGNMENT? PROJECT? GET TO IT. I BELIEVE IN YOU.",
                   "DON’T YOU EVER FUCKING GIVE UP, DO YOU HEAR ME?",
                   "SUP. YOU ARE COOL. THAT’S ALL, AS YOU WERE.",
                   "IS THERE SOMETHING YOU CAN START WORKING ON SOON AND SHOULD?",
                   "HEY, YOU ARE AN AMAZING PERSON. THAT’S ALL.",
                   "HAVE YOU DRANK WATER? DRINK MORE WATER?",
                   "HAVE YOU ATE TODAY? PLEASE EAT SOME FOOD.",
                   "HATERS GONNA DRINK THE HATER-AID NO MATTER WHAT, IGNORE THEM.",
                   "STICKS AND STONES MAY BREAK YOUR BONES BUT DON’T YOU LET SOME ASSHOLE HURT YOU.",
                   "WHAT’S GOOD? YOU GOOD? YEAH YOU ARE.",
                   "U R LOVED.",
                   "HAVE A GREAT DAY. YOU DESERVE TO HAVE ONE.",
                   "EAT YOUR GOSH DARN VEGGIES, YOU NEED THEM.",
                   "MAKE SURE TO GET 7 HOURS OR MORE OF SLEEP, YOU DINGUS.",
                   "DONT. FORGET. TO. CALL. YOUR. MOM."]


if __name__ == "__main__":
    """
    this method is just meant to check that all list values
    are valid by plain printing
    """
    for value in tweets:
        print(value)

    for value in worriedReplies:
        print(value)

    for value in sickReplies:
        print(value)

    for value in lonelyReplies:
        print(value)
