"""
tweets for ToughLoveBot by elias g. and elliot p. These tweets are by elliot p.
with minimal editing by elias g.

authors: elias g. and elliot p.
version: 21.11.16
"""
"""
COLUMN A:
	⁃	HEY, REMEMBER TO 
	⁃	GURL, YOU BETTER 
	⁃	MAKE SURE YOU 
	⁃	GUESS WHAT TIME IT IS. IT’S TIME FOR YOU TO 
	⁃	BRO, I NEED YOU TO 
	⁃	YOU SHOULD REALLY 
	⁃	DO ME A FAVOR AND 

COLUMN B:
	⁃	GO OUTSIDE. 
	⁃	DRINK SOME WATER. 
	⁃	TAKE SOME DEEP BREATHS. 
	⁃	TRY AND FIND SOME NEW MUSIC. 
	⁃	TALK TO SOMEONE ABOUT THOSE FEELINGS. 
	⁃	TAKE A POWER NAP. 
	⁃	EAT ONE HEALTHY THING. 
	⁃	TAKE A MINUTE TO GET YOUR HEAD STRAIGHT. 
	⁃	EAT SOMETHING. 

COLUMN C:

	⁃	I’M FORCING YOU TO DO THIS BECAUSE I LOVE YOU.
	⁃	I’LL KNOW IF YOU DIDN’T.
	⁃	YOU’LL DEFINITELY FEEL BETTER AFTERWARDS.
	⁃	I LOVE YOU.
	⁃	YOU’RE DOING GREAT.
	⁃	DO IIIIIIIIIT.
	⁃	YOU KNOW I GOT YOUR BACK.
	⁃	THANKS IN ADVANCE.
	⁃	OKAY?
  """

statusTweets = [
                #DO A THING
                "ARE YOU BREATHING FASTER THAN NORMAL? CALM THAT MESS DOWN. SLOW, EVEN BREATHS.",
                "BREATHE. JUUUST BREATHE.",
                "CALL YOUR DAD. HE LOVES YOU AND WANTS TO KNOW HOW YOU ARE DOING.",
                "CALL YOUR MOM. SHE LOVES YOU AND WANTS TO KNOW HOW YOU ARE DOING.",
                "CLEAN OUT YOUR INBOX. IT'LL GIVE YOU PEACE OF MIND.",
                "DID YOU EAT YET TODAY? PLEASE EAT TODAY.",
                "DO NOT EAT THAT HORSESHIT. EAT SOME FRUIT OR SOMETHING. YOU'RE STILL GOING TO NEED THESE ORGANS WHEN YOU'RE EIGHTY.",
                "DO YOU HAVE MEDS. IF SO, REMEMBER TO TAKE THEM. IF NOT, EAT A VITAMIN OR SOMETHING.",
                "DRINK SOME FUCKING WATER. YOU'RE DEHYDRATED AND IT'S MAKING YOU GRUMPY.",
                "GIVE SOMEONE A HIGH FIVE. THE TRICK IS TO FOCUS ON THEIR ELBOWS, THEN YOU NEVER MISS.",
                "GO OUTSIDE AND FIND SOME RUNNING WATER AND MEDITATE.",
                "GO OUTSIDE AND LOOK AT SOME PLANTS AND NATURE AND SHIT.",
                "GO OUTSIDE AND LOOK AT SOME PLANTS AND SHIT. NOTICE HOW THE DIRT SMELLS.",
                "GO OUTSIDE AND SIT UNDER A TREE AND THINK HAPPY THOUGHTS.",
                "MAKE A SNACK. NO, NOT SOMETHING SHIT LIKE THAT. SOMETHING ACTUALLY GOOD FOR YOU. SOMETHING WITH FIBER.",
                "MAKE THEM RESPECT YOUR PRONOUNS. DO NOT TOLERATE THEIR BULLSHIT.",
                "MAYBE READ GODDAMN A BOOK ONCE IN AWHILE.",
                "NOTICE HOW THE DIRT SMELLS. NICE.",
                "NOTICE HOW THE SUNLIGHT SHINES THROUGH THE LEAVES. SO PRETTY.",
                "PUT SOME SOCKS NEAR THE HEATER SO THAT THEY'RE ALL WARM LATER. SO TOASTY.",
                "REMEMBER THAT COUSIN YOU PLAYED WITH A LOT WHEN YOU WERE A KID? CALL THEM AND CATCH UP.",
                "REMEMBER TO TEXT WHOEVER BACK.",
                "SPEAK UP, EVEN IF IT MEANS YOUR VOICE CRACKS. YOU'RE STRONG.",
                "STOP COMING UP WITH REASONS WHY NOT AND JUST DO IT ALREADY.",
                "TAKE A MENTAL HEALTH DAY. SAY YOU'RE SICK OR SOMETHING. REMEMBER, THE MOST COMMON AND BELIEVABLE ALIMENT IS 'STOMACH STUFF'.",
                "TAKE SOME DEEP-ASS BREATHS.",
                "TALK TO SOMEONE. STEWING IN YOUR OWN EMOTIONS WILL ONLY JACK UP THOSE FEELINGS OF ISOLATION.",
                "THAT CLOUD LOOKS LIKE A WEIRD DUCK. NEAT.",
                "YOU KNOW THAT THING YOU'E BEEN PUTTING OFF DOING FOR WEEKS. DO IT. RIGHT NOW. NO EXCUSES.",
                "YOU'VE BEEN SITTING IN THAT CHAIR FOR A WHILE. STAND UP AND WALK AROUND A LITTLE. MAYBE DO SOME PUSH-UPS.",

  
                #POSITIVE AFFIRMATION
                "FIGHT THE GOOD FIGHT. DO YOUR HOMEWORK.",
                "FIGHT THE GOOD FIGHT. STAND UP FOR YOURSELF AND WHAT YOU BELIEVE IN.",
                "FUCK WHAT THE HATERS SAID.",
                "HEY. I LOVE YOU.",
                "HEY. SOMETIMES THINGS ARE GOING TO BE HARD, BUT THAT WONâ��T LAST FOREVER. YOU JUST NEED TO BE STRONG, AND  EVENTUALLY IT'LL PASS.",
                "HEYYYYY. JUST A REMINDER THAT YOU HAVE TALENTS UNIQUE TO YOU, THAT NO ONE ELSE IN THE WORLD HAS.",
                "I FUCKING BELIEVE IN YOU.",
                "IF YOU ARE STRUGGLING, YOU ARE MAKING PROGRESS. KEEP FIGHTING.",
                "IF YOU ARE STRUGGLING AND HAVE NO ONE TO GO TO, REMEMBER THERE ARE SUPPORT GROUPS YOU CAN REACH OUT TO.",
                "IT'S OKAY TO SEEK EMOTIONAL SUPPORT FROM THE PEOPLE YOU LOVE. NEEDING THE HELP OF OTHERS ISN'T A SIGN OF WEAKNESS.",
                "MEND THE FIRST BREAK, KILL THE FIRST SNAKE, AND CONQUER EVERYTHING YOU UNDERTAKE.",
                "NEVER LET SOMEONE MAKE YOU FEEL BAD ABOUT WHERE YOU ARE FROM, WHAT GENDER YOU ID WITH, OR THE TONE OF YOUR SKIN.",
                "NOTHING LASTS FOREVER, BAD OR GOOD. ENJOY THE GOOD WHILE IT LASTS AND KNOW THE BAD IS ALWAYS TEMPORARY.",
                "REMEMBER THAT SOMETIMES ALL YOU NEED TO DO IS KEEP ON KEEPING ON.",
                "REMEMBER THAT THIS ISN'T JUST A BOT. A PERSON MADE THIS, AND THAT PERSON LOVES YOU, WHOEVER YOU ARE.",
                "THE REPORTS ARE IN AND YOU'RE DOING GREAT, KEEP IT UP.",
                "THE REPORTS ARE IN AND YOU GOT THIS. KEEP HOLDING ON.",
                "WHEREVER YOU WIND UP IN LIFE, YOU'LL FIND A WAY TO BE HAPPY, AND BE CONTENTED WITH THE CHOICES YOU MADE.",
                "YOU ARE AMAZING, FUCK YEAAAAH. 🤘🤘🤘",
                "YOUR FRIENDS LOVE YOU. DOUBTING THAT WILL ONLY MAKE THINGS WORSE. RECEIVING AFFECTION ISN'T A WEAKNESS.",
                "YOU'RE NEVER AS ALONE AS YOU MIGHT THINK YOU ARE.",

                #MISC

                "ARE YOU HUNGRY OR ARE YOU JUST BORED. REALLY THINK ABOUT IT.",
                "AT THE END OF THE DAY, THE DECISIONS THAT MATTER THE MOST ARE THOSE THAT MAKE YOU HAPPY.",
                "HERE IS A LINK TO A VIDEO OF A CAT AND A CHICKEN WHO ARE FRIENDS. LOOK AT IT. SO CUTE. https://www.youtube.com/watch?v=sNYIAQcCF9k",
                "IF YOU DON'T HAVE A DAD, THAT'S OKAY. IT'S NOT YOUR FAULT AND IT'S HIS LOSS.",
                "IF YOU DON'T HAVE A MOM, THAT'S OKAY. IT'S NOT YOUR FAULT AND IT'S HER LOSS.",
                "IT'S NOT OKAY FOR YOUR SIGNIFICANT OTHER TO BLAME YOU FOR EVERYTHING.",
                "LOVE SOMEONE WHO LOVES YOU BACK. SETTLE FOR NO LESS, NEVER EVER.",
                "NOT STRAIGHT? GREAT. DON'T LET ANYONE LET YOU FEEL WRONG ABOUT THAT.",
                "REMEMBER, YOU DESERVE TO FEEL GOOD TOO.",
                "REMEMBER THAT ONE JERK? YEAH, THEY CAN GO TO HELL AND THEIR OPINION DOESN'T MATTER.",
                "YOU DESERVE TO FEEL LOVED AND TO BE LOVED. DON'T DATE SOMEONE WHO MAKES YOU FEEL OTHERWISE.",
                "YOU KNOW THAT PERSON YOU HATE. WELL I TRUST YOUR JUDGMENT ENOUGH TO HATE THEM TOO. THEY'RE THE WORST.",]

worriedReplies = ["AS LONG AS YOU NEVER GIVE UP, YOU WON'T BE TAKEN DOWN WITHOUT A FIGHT.",
                  "BREATHE DEEPLY."
                  "FEAR ONLY CLOUDS THE MIND WITH DOUBT. SEE CLEARLY. BREATHE IN.",
                  "I LOVE YOU. AND SO DO OTHERS.",
                  "IT MAY NOT BE OKAY NOW, BUT IT WILL BE SOON.",
                  "IT'S GOING TO BE OKAY",
                  "THINGS ARE NEVER AS BAD AS THEY SEEM.",
                  "THINGS WILL GET BETTER. I PROMISE.",
                  "YOU CAN SURVIVE THIS.",
                  "YOUR ANXIETIES ONLY DECEIVE YOU.",
                  "YOU'RE STRONG. YOU CAN DO THIS.",
                  "YOU'RE STRONG. YOU CAN FIGHT BACK.",]

sickReplies = ["BREATHE DEEPLY."
               "FOCUS INWARD AND ONWARD.",
               "HEAL THE MIND AND THE REST WILL FOLLOW. GIVE YOURSELF A BREAK.",
               "I LOVE YOU. AND SO DO OTHERS.",
               "IT MAY NOT BE OKAY NOW, BUT IT WILL BE SOON.",
               "IT'S GOING TO BE OKAY",
               "IT'S OKAY TO SLOW DOWN AND GIVE YOURSELF TIME TO RECOVER.",
               "PAIN EXISTS ONLY IN THE MIND. YOU GOT THIS.",
               "THE BODY'S ABILITY TO HEAL ITSELF IS BETTER THAN ANYTHING MADE BY HUMAN HANDS.",
               "THERE ARE OTHERS YOU CAN RELY ON FOR SUPPORT.",
               "THINGS WILL GET BETTER. I PROMISE.",
               "YOU CAN SURVIVE THIS.",
               "YOU'RE STRONG. YOU CAN DO THIS.",]

lonelyReplies = ["BREATHE DEEPLY."
                 "DON'T BE AFRAID TO REACH OUT.",
                 "IF YOU'VE BEEN HURT IN THE PAST, KNOW THAT YOU SURVIVED IT. AND THIS TIME, YOU CAN PREVENT IT.",
                 "I LOVE YOU. AND SO DO OTHERS.",
                 "IT MAY NOT BE OKAY NOW, BUT IT WILL BE SOON.",
                 "IT'S GOING TO BE OKAY",
                 "MORE PEOPLE LOVE YOU THAN YOU KNOW.",
                 "OTHER PEOPLE ARE NEVER AS SCARY AS THEY SEEM.",
                 "THINGS WILL GET BETTER. I PROMISE.",
                 "WANTING TO BE LOVED IS NOT A WEAKNESS.",
                 "YOU CAN SURVIVE THIS.",
                 "YOU'RE STRONG. YOU CAN DO THIS.",]

followerReplies = ["DON'T. FORGET. TO. CALL. YOUR. MOM."
                   "DON'T YOU EVER FUCKING GIVE UP, DO YOU HEAR ME?",
                   "DO YOU HAVE SOME KIND OF ASSIGNMENT? PROJECT? GET TO IT. I BELIEVE IN YOU.",
                   "EAT YOUR GOSH DARN VEGGIES, YOU NEED THEM.",
                   "HATERS GONNA DRINK THE HATER-AID NO MATTER WHAT, IGNORE THEM.",
                   "HAVE A GREAT DAY. YOU DESERVE TO HAVE ONE.",
                   "HAVE YOU EATEN TODAY? PLEASE EAT SOME FOOD.",
                   "HAVE YOU DRANK WATER? DRINK MORE WATER?",
                   "HEY, YOU ARE AN AMAZING PERSON. THAT'S ALL.",
                   "IS THERE SOMETHING YOU CAN START WORKING ON SOON AND SHOULD?",
                   "IS YOUR SHIT TOGETHER? GET YOUR SHIT TOGETHER. YOU CAN DO IT.",
                   "MAKE SURE TO GET 7 HOURS OR MORE OF SLEEP, YOU DINGUS.",
                   "STICKS AND STONES MAY BREAK YOUR BONES BUT DON'T YOU LET SOME ASSHOLE HURT YOU.",
                   "SUP. YOU ARE COOL. THAT'S ALL, AS YOU WERE.",
                   "U R LOVED.",
                   "WHAT'S GOOD? YOU GOOD? YEAH YOU ARE.",
                   "YOU ARE AN AMAZING PERSON, YOU GOT THIS.",]


if __name__ == "__main__":
    """
    this method is just meant to check that all list values
    are valid by plain printing
    """
    for value in tweets:
        print(value)

    for value in worriedReplies:
        print(value)

    for value in sickReplies:
        print(value)

    for value in lonelyReplies:
        print(value)
