"""
tweets for ToughLoveBot by elias g. and elliot p. These tweets are by elliot p.
with minimal editing by elias g.

authors: elias g. and elliot p.
version: 21.11.16
"""
import sys

tweets = ["NOTICE HOW THE DIRT SMELLS|NOTICE HOW THE SUNLIGHT SHINES THROUGH THE LEAVES. SO PRETTY|THAT CLOUD LOOKS LIKE A WEIRD DUCK.",
          "HEY. SOMETIMES THINGS ARE GOING TO BE HARD, BUT THAT WON’T LAST FOREVER. YOU JUST NEED TO BE STRONG, AND  EVENTUALLY IT'LL PASS.",
          "DO NOT EAT THAT HORSESHIT. EAT SOME FRUIT OR SOMETHING. YOU'RE STILL GOING TO NEED THESE ORGANS WHEN YOU'RE EIGHTY.",
          "IT’S OKAY TO SEEK EMOTIONAL SUPPORT FROM THE PEOPLE YOU LOVE. NEEDING THE HELP OF OTHERS IS NOT A SIGN OF WEAKNESS.",
          "REMEMBER THAT THIS ISN’T JUST A BOT. A PERSON MADE THIS, AND THAT PERSON LOVES YOU, WHOEVER YOU ARE.",
          "REMEMBER TO TEXT WHOEVER BACK",
          "DRINK SOME FUCKING WATER. YOU'RE DEHYDRATED AND IT'S MAKING YOU GRUMPY.",
          "MAYBE READ GODDAMN A BOOK ONCE IN AWHILE.",
          "TAKE SOME DEEP-ASS BREATHS.",
          "GO OUTSIDE AND LOOK AT SOME PLANTS AND SHIT. NOTICE HOW THE DIRT SMELLS.",
          "I FUCKING BELIEVE IN YOU.",
          "TALK TO SOMEONE. STEWING IN YOUR OWN EMOTIONS WILL ONLY INCREASE FEELINGS OF ISOLATION.",
          "YOU’VE BEEN SITTING IN THAT CHAIR FOR A WHILE. STAND UP AND WALK AROUND A LITTLE. MAYBE DO SOME PUSH-UPS.",
          "STOP COMING UP WITH REASONS WHY NOT AND JUST DO IT ALREADY.",
          "MAKE A SNACK. NO, NOT SOMETHING SHIT LIKE THAT. SOMETHING ACTUALLY GOOD FOR YOU. SOMETHING WITH FIBER.",
          "ASKING FOR HELP IS PERFECTLY VALID. NO ONE WILL THINK LESS OF YOU FOR IT.",
          "YOU KNOW THAT THING YOU’VE BEEN PUTTING OFF DOING FOR WEEKS. DO IT. RIGHT NOW. NO EXCUSES.",
          "TAKE A MENTAL HEALTH DAY. SAY YOU’RE SICK OR SOMETHING. REMEMBER, THE MOST COMMON AND BELIEVABLE ALIMENT IS “STOMACH STUFF”.",
          "PUT SOME SOCKS NEAR THE HEATER SO THAT THEY’RE ALL WARM LATER. SO TOASTY.",
          "DO YOU HAVE MEDS. IF SO, REMEMBER TO TAKE THEM. IF NOT, EAT A VITAMIN OR SOMETHING.",
          "BREATHE. JUUUST BREATHE.",
          "YOU’RE NEVER AS ALONE AS YOU MIGHT THINK YOU ARE.",
          "ARE YOU BREATHING FASTER THAN NORMAL? CALM THAT MESS DOWN. SLOW, EVEN BREATHS.",
          "YOU KNOW THAT PERSON YOU HATE. WELL I TRUST YOUR JUDGMENT ENOUGH TO HATE THEM TOO. THEY’RE THE WORST.",
          "YOUR FRIENDS LOVE YOU. DOUBTING THAT WILL ONLY MAKE THINGS WORSE. RECEIVING AFFECTION IS NOT A WEAKNESS.",
          "NOTHING LASTS FOREVER, BAD OR GOOD. ENJOY THE GOOD WHILE IT LASTS AND KNOW THE BAD IS ALWAYS TEMPORARY.",
          "HEY. I LOVE YOU.",
          "HEYYYYY. JUST A REMINDER THAT YOU HAVE TALENTS UNIQUE TO YOU, THAT NO ONE ELSE IN THE WORLD HAS.",
          "GIVE SOMEONE A HIGH FIVE. THE TRICK IS TO FOCUS ON THEIR ELBOWS, THEN YOU NEVER MISS.",
          "CLEAN OUT YOUR INBOX. IT’LL GIVE YOU PEACE OF MIND.",
          "HERE IS A LINK TO A VIDEO OF A CAT AND A CHICKEN WHO ARE FRIENDS. LOOK AT IT. SO CUTE. https://www.youtube.com/watch?v=sNYIAQcCF9k",
          "GO OUTSIDE AND (LOOK AT SOME PLANTS AND SHIT|FIND SOME RUNNING WATER|SIT UNDER A NICE TREE).",
          "ARE YOU HUNGRY OR ARE YOU JUST BORED. REALLY THINK ABOUT IT.",
          "WHEREVER YOU WIND UP IN LIFE, YOU’LL FIND A WAY TO BE HAPPY, AND BE CONTENTED WITH THE CHOICES YOU MADE."]

originalDictionaryThatIConverted = {"0": "HEY. SOMETIMES THINGS ARE GOING TO BE HARD, BUT THAT WON’T LAST FOREVER. YOU JUST NEED TO BE STRONG, AND  EVENTUALLY IT'LL PASS.",
             "1": "I FUCKING BELIEVE IN YOU.",
             "2": "DO NOT EAT THAT HORSESHIT. EAT SOME FRUIT OR SOMETHING. YOU'RE STILL GOING TO NEED THESE ORGANS WHEN YOU'RE EIGHTY.",
             "3": "STOP COMING UP WITH REASONS WHY NOT AND JUST DO IT ALREADY.",
             "4": "HEY. I LOVE YOU.",
             "5": "DO YOU HAVE MEDS. IF SO, REMEMBER TO TAKE THEM. IF NOT, EAT A VITAMIN OR SOMETHING.",
             "6": "DRINK SOME FUCKING WATER. YOU'RE DEHYDRATED AND IT'S MAKING YOU GRUMPY.",
             "7": "YOUR FRIENDS LOVE YOU. DOUBTING THAT WILL ONLY MAKE THINGS WORSE. RECEIVING AFFECTION IS NOT A WEAKNESS.",
             "8": "GO OUTSIDE AND LOOK AT SOME PLANTS AND SHIT. NOTICE HOW THE DIRT SMELLS.",
             "9": "HERE IS A LINK TO A VIDEO OF A CAT AND A CHICKEN WHO ARE FRIENDS. LOOK AT IT. SO CUTE. https://www.youtube.com/watch?v=sNYIAQcCF9k",
             "10": "YOU KNOW THAT PERSON YOU HATE. WELL I TRUST YOUR JUDGMENT ENOUGH TO HATE THEM TOO. THEY’RE THE WORST.",
             "11": "TAKE A MENTAL HEALTH DAY. SAY YOU’RE SICK OR SOMETHING. REMEMBER, THE MOST COMMON AND BELIEVABLE ALIMENT IS “STOMACH STUFF”.",
             "12": "TAKE SOME DEEP-ASS BREATHS.",
             "13": "IT’S OKAY TO SEEK EMOTIONAL SUPPORT FROM THE PEOPLE YOU LOVE. NEEDING THE HELP OF OTHERS IS NOT A SIGN OF WEAKNESS.",
             "14": "REMEMBER TO TEXT WHOEVER BACK",
             "15": "CLEAN OUT YOUR INBOX. IT’LL GIVE YOU PEACE OF MIND.",
             "16": "YOU’VE BEEN SITTING IN THAT CHAIR FOR A WHILE. STAND UP AND WALK AROUND A LITTLE. MAYBE DO SOME PUSH-UPS.",
             "17": "PUT SOME SOCKS NEAR THE HEATER SO THAT THEY’RE ALL WARM LATER. SO TOASTY.",
             "18": "GO OUTSIDE AND (LOOK AT SOME PLANTS AND SHIT|FIND SOME RUNNING WATER|SIT UNDER A NICE TREE).",
             "19": "NOTICE HOW THE DIRT SMELLS|NOTICE HOW THE SUNLIGHT SHINES THROUGH THE LEAVES. SO PRETTY|THAT CLOUD LOOKS LIKE A WEIRD DUCK.",
             "20": "MAKE A SNACK. NO, NOT SOMETHING SHIT LIKE THAT. SOMETHING ACTUALLY GOOD FOR YOU. SOMETHING WITH FIBER.",
             "21": "MAYBE READ GODDAMN A BOOK ONCE IN AWHILE.",
             "22": "REMEMBER THAT THIS ISN’T JUST A BOT. A PERSON MADE THIS, AND THAT PERSON LOVES YOU, WHOEVER YOU ARE.",
             "23": "ARE YOU HUNGRY OR ARE YOU JUST BORED. REALLY THINK ABOUT IT.",
             "24": "HEYYYYY. JUST A REMINDER THAT YOU HAVE TALENTS UNIQUE TO YOU, THAT NO ONE ELSE IN THE WORLD HAS.",
             "25": "ARE YOU BREATHING FASTER THAN NORMAL? CALM THAT MESS DOWN. SLOW, EVEN BREATHS.",
             "26": "TALK TO SOMEONE. STEWING IN YOUR OWN EMOTIONS WILL ONLY INCREASE FEELINGS OF ISOLATION.",
             "27": "WHEREVER YOU WIND UP IN LIFE, YOU’LL FIND A WAY TO BE HAPPY, AND BE CONTENTED WITH THE CHOICES YOU MADE.",
             "28": "GIVE SOMEONE A HIGH FIVE. THE TRICK IS TO FOCUS ON THEIR ELBOWS, THEN YOU NEVER MISS.",
             "29": "ASKING FOR HELP IS PERFECTLY VALID. NO ONE WILL THINK LESS OF YOU FOR IT.",
             "30": "BREATHE. JUUUST BREATHE.",
             "31": "NOTHING LASTS FOREVER, BAD OR GOOD. ENJOY THE GOOD WHILE IT LASTS AND KNOW THE BAD IS ALWAYS TEMPORARY.",
             "32": "YOU’RE NEVER AS ALONE AS YOU MIGHT THINK YOU ARE.",
             "33": "YOU KNOW THAT THING YOU’VE BEEN PUTTING OFF DOING FOR WEEKS. DO IT. RIGHT NOW. NO EXCUSES."}

with open("list.txt", "w") as file:
    string = str(toughLove.values())
    file.write(string)
    file.close()
