"""
this is just a script that tests the various functions of Tweepy. Unless
commented otherwise, the method works, so feel free to copy for your own.
author: elias g
version: 26.11.16
"""

import tweepy as ty
import arrow
import random
from toughLoveTweets import (statusTweets, worriedReplies, lonelyReplies,
                             sickReplies, followerReplies)
from toughLoveSecret import (CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN,
                             ACCESS_SECRET)


def setTwitterAuth():
    """
    obtains authorization from twitter API
    """
    # sets the auth tokens for twitter using tweepy
    auth = ty.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
    auth.set_access_token(ACCESS_TOKEN, ACCESS_SECRET)
    api = ty.API(auth)
    return api


def getFollowers(api):
    followers = ty.Cursor(api.followers).items()
    for follower in followers:
        print(follower.name)


def getRandomFollower(api, bot):
    """
    chooses a random follower and tweets at them
    """
    # Cool trick found on SX, use list comprehension to turn pagination into
    # normal list for the purposes of making choosing a random person easier
    message = ("Hey, this is a test tweet generated by the creator! Sorry to"
               " bother you!")
    tweet = ".@{} " + message

    followers = [follower for follower in ty.Cursor(api.followers).items()]
    randomFollower = followers[random.randint(0, len(followers) - 1)]
    followerHandle = randomFollower.screen_name
    api.update_status(tweet.format(followerHandle))


def getSearch(api, search):
    """
    gets search results of the string, search, returns 100 tweets.
    """
    # list comprehension ftw, makes paginated cursor into normal list which is
    # better suited for this use case.
    searchResults = [status for status in ty.
                     Cursor(api.search, q=search).items(100)]
    for result in searchResults:
        print(len(searchResults))
        print(result.text)
        print(result.user.screen_name)

if __name__ == "__main__":
    api = setTwitterAuth()
    # getSearch(api, "\"I am sad\"")
    # getFollowers(api)
    # this gets the user object
    bot = api.me()
    getRandomFollower(api, bot)
    # bot account's id
    # print(bot.id)
    # bot's # of followers
    # print(bot.followers_count)
